### ISSUE TITLE
logout() times out (callback not called). 

### ISSUE THREAD

**Issue by eblume** [eblume/node-gmail#2]
Currently the test suite (`npm test`) fails due to timing out. It seems that the imap connection's logout command is not calling the callback, perhaps due to some sort of connection issue.

**Comment by mscdex** [comment]
This is the test I was using that works for me:

``` javascript
var gm = new (require('./lib/gmail').GMailInterface)();

gm.connect('username', 'password', function(err) {
  if (err) throw err;
  gm.logout(function(err) {
    if (err) throw err;
    console.error('Logout callback called!');
  });
});
```

My guess is there is either something wrong with the usage of the test framework or that pulling in 'All Mail' takes a long time for the test account you're using (especially when you're retrieving every entire (raw) message with apply_all).

**Comment by eblume** [comment]
You've nailed it, I think - apply_all is a terrible function that I thought was 'all I needed', but all evidence to the contrary!

I'll have to double-down and write a more efficient api.

Incidentally, is there a way with the imap library to cancel an in-progress fetch?

**Comment by mscdex** [comment]
No, the current IMAP spec does not support cancelling an in-progress fetch.

EDIT: However, imap.search() passes an array of ids to its callback on success. So one thing you could do to allow more flexibility is to fetch each one of them individually, one after the other, instead of all of them in one go. How you determine when to stop advancing to the next message is up to you, but you could do something like checking the return value of the function passed to apply_all() -- if the function returns false, do not fetch any more additional messages.

**Comment by eblume** [comment]
Ok, nailed it down. Thanks for the tips, and thanks also for the great library. Hopefully node-gmail will be a good compliment to your library for those parsing google. Obviously it isn't that useful yet.
